### ISSUE TITLE
timezones are misordered

### ISSUE THREAD

**Issue by brimwats** [ms3056/Tokei#2]
I am trying to make this read in order of increasing time, so MST, CST, EST and then GMT. But GMT moves itself to the left no matter what because it's the next day

![image](https://github.com/ms3056/Tokei/assets/73113656/c31b3235-5ae7-457c-9ab8-be7f4ebaac0b)

**Comment by ms3056** [comment]
This is current by design - I prefer to have the timezones closest to me on the RIGHT and increase to the left. 

I will consider an option to reverse the order.

**Comment by ms3056** [comment]
I've got a change I am testing to allow you to reverse the order. Let me make sure it doesn't break anything and you will have it in the next couple of days. Thanks for the suggestion. 
![image](https://github.com/ms3056/Tokei/assets/23712700/eb7e0c9d-4c55-41e3-8c6b-639125b13b80)

**Comment by ms3056** [comment]
Implemented in 0.7.0! Thanks for the suggestion. 

https://github.com/ms3056/Tokei/releases/tag/untagged-b86adc1ed437944f50a6

**Comment by brimwats** [comment]
I'm not sure I understand, GMT is farther away from me (london to vancouver) than EST (vancouver to NYC), but I'll try the new version!

**Comment by ms3056** [comment]
The sort algorithm is very simple - it just does a numerical sort on the UTC offset. You can sort, now, left to right or right to left. 

This is the sort - very simple. If enough people ask for it, I may offer another setting to turn OFF the sort and simply display in the order in the settings. 

```typescript
	private sortTimeZones(): TimezonePair[] {
		const currentOffset = DateTime.local().offset;

		let sortedTimeZones = this.plugin.settings.timeZonePairs
			.slice()
			.sort((a, b) => {
				const offsetA = parseFloat(a.offset);
				const offsetB = parseFloat(b.offset);

				const diffA = Math.abs(currentOffset - offsetA);
				const diffB = Math.abs(currentOffset - offsetB);

				return diffB - diffA;
			});

		// If reverseTimezoneOrder is false, reverse the sorted array
		if (!this.plugin.settings.reverseTimezoneOrder) {
			sortedTimeZones = sortedTimeZones.reverse();
		}

		return sortedTimeZones;
	}
	```
