### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by grewanhassan** [ms3056/Tokei#4]
Hi, 

I have recently noticed that Obsidian is constantly using 0.3 - 0.6% of my CPU power in the background, even when I have not used it for hours.

After painstakingly checking all my plugins, I have now found out through the exclusion process that the problem is the Tokei plugin.

best

![Screenshot_20240207_192642](https://github.com/ms3056/Tokei/assets/69326136/84361c9a-c305-4435-a741-ba55fdc5a6d7)

**Comment by ms3056** [comment]
Hi! I have noticed this too. I think I thought it was my weather plugin, but, I think it is due to how I need to update this clock once a second. I am testing a fix now.

**Comment by ms3056** [comment]
Did what I could do update only things that change - but - note - alot changes every second when you have the time and multiple timezones. Changed in https://github.com/ms3056/Tokei/releases/tag/0.8.0
